import { writeFile, mkdir } from "node:fs/promises";
import { readFileSync } from "node:fs";
import path from "node:path";

import { CLUBS } from "./clubs.mjs";
import { fetchWikitext } from "./wiki.mjs";
import { parseSeason, fixtureIdentity, CLUB_ALIASES } from "./parse.mjs";
import { buildIcs } from "./ics.mjs";

const ROOT = path.resolve(import.meta.dirname, "..");
const force = process.argv.includes("--force");

function hash8(text) {
  let h = 0;
  for (const ch of text) h = (h * 31 + ch.codePointAt(0)) >>> 0;
  return h.toString(36).padStart(7, "0");
}

// UIDs must stay stable between refreshes, so derive them from the fixture
// itself. Some pages reuse one report URL for a whole matchday, hence the
// date/opponent salt and the final uniqueness pass.
function makeIdFactory() {
  const used = new Set();
  return (match) => {
    const urlId = match.report && match.report.match(/\/(?:match|game)\/(\d+)/)?.[1];
    const salt = hash8(`${match.date}|${match.homeTeam}|${match.awayTeam}`);
    let id = urlId ? `${match.club}-${urlId}-${salt}` : `${match.club}-w${salt}`;
    let n = 2;
    while (used.has(id)) id = `${match.club}-w${salt}-${n++}`;
    used.add(id);
    return id;
  };
}

function statusOf(match, now) {
  if (match.score) return "played";
  if (match.kickoffUtc) {
    return new Date(match.kickoffUtc).getTime() < now.getTime() ? "unknown-result" : "upcoming";
  }
  return match.date && match.date < now.toISOString().slice(0, 10)
    ? "unknown-result"
    : "upcoming";
}

const now = new Date();
const idOf = makeIdFactory();
const all = [];
const report = { skipped: [], duplicates: [], noDate: [], byClub: {} };

for (const club of CLUBS) {
  const entry = await fetchWikitext({ page: club.page, force });
  const { matches, skipped } = parseSeason(entry.wikitext, club);
  report.skipped.push(...skipped.map((s) => ({ club: club.id, ...s })));

  const seen = new Map();
  for (const m of matches) {
    if (!m.date) {
      report.noDate.push({ club: club.id, competition: m.competition, opponent: m.opponent });
      continue;
    }
    const key = `${m.competition}|${m.round}|${m.opponent}|${m.date}`;
    if (seen.has(key)) {
      report.duplicates.push({ club: club.id, key });
      continue;
    }
    seen.set(key, true);
    const full = {
      ...m,
      clubName: club.name,
      id: idOf(m),
      status: statusOf(m, now),
      fixtureKey: fixtureIdentity(m),
      sourcePage: entry.title,
    };
    all.push(full);
  }

  const played = all.filter((m) => m.club === club.id && m.status === "played").length;
  const upcoming = all.filter((m) => m.club === club.id && m.status === "upcoming").length;
  const odd = all.filter((m) => m.club === club.id && m.status === "unknown-result").length;
  report.byClub[club.id] = {
    total: seen.size,
    played,
    upcoming,
    unknownResult: odd,
    comps: [...new Set(all.filter((m) => m.club === club.id).map((m) => m.competition))],
  };
  console.log(
    `${club.name.padEnd(22)} total=${String(seen.size).padStart(3)} played=${String(played).padStart(2)} upcoming=${String(upcoming).padStart(2)} unknown=${odd}`
  );
}

all.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0));

const dataDir = path.join(ROOT, "data");
const calDir = path.join(ROOT, "calendar");
await mkdir(dataDir, { recursive: true });
await mkdir(calDir, { recursive: true });

const generatedAt = now.toISOString();
const payload = {
  generatedAt,
  season: "2026-27",
  source: "Wikipedia club season pages",
  clubs: CLUBS.map(({ id, name, short, color, page }) => ({
      id,
      name,
      short,
      color,
      page,
      aliases: CLUB_ALIASES[id] || [name],
    })),
  matches: all,
};

await writeFile(path.join(dataDir, "matches.json"), JSON.stringify(payload, null, 2));
await writeFile(
  path.join(dataDir, "matches.js"),
  `// Generated by \`npm run refresh\` at ${generatedAt}\nwindow.MATCHES_DATA = ${JSON.stringify(payload)};\n`
);

const perClub = CLUBS.map((club) => ({
  club,
  file: path.join(calDir, `${club.id}.ics`),
  matches: all.filter((m) => m.club === club.id),
}));

// A tie between two tracked clubs is one calendar entry, not two.
const combined = [];
const byFixture = new Map();
for (const m of all) {
  const prev = byFixture.get(m.fixtureKey);
  if (prev) {
    prev.trackedClubs.push(m.club);
    prev.trackedClubNames.push(m.clubName);
    continue;
  }
  const row = { ...m, trackedClubs: [m.club], trackedClubNames: [m.clubName] };
  byFixture.set(m.fixtureKey, row);
  combined.push(row);
}
combined.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0));
console.log(
  `combined calendar: ${combined.length} entries (${all.length - combined.length} shared fixtures merged)`
);

const files = [
  { file: path.join(calDir, "all-clubs.ics"), matches: combined, name: "Sports Calendar — all clubs" },
  ...perClub.map(({ file, matches, club }) => ({ file, matches, name: club.name })),
];
for (const f of files) {
  await writeFile(f.file, buildIcs({ ...f, generatedAt }));
}

const timeConfidence = {};
for (const m of all) timeConfidence[m.timeConfidence] = (timeConfidence[m.timeConfidence] || 0) + 1;

console.log(`\nmatches: ${all.length}   ics files: ${files.length}`);
console.log("time confidence:", JSON.stringify(timeConfidence));
console.log("skipped blocks:", report.skipped.length);
for (const s of report.skipped.slice(0, 10)) console.log("  ", JSON.stringify(s));
console.log("duplicates:", report.duplicates.length);
console.log("undated:", report.noDate.length);
for (const s of report.noDate.slice(0, 10)) console.log("  ", JSON.stringify(s));

const comps = {};
for (const m of all) comps[m.competition] = (comps[m.competition] || 0) + 1;
console.log("\ncompetitions:");
for (const [k, v] of Object.entries(comps).sort((a, b) => b[1] - a[1])) {
  console.log(`  ${String(v).padStart(3)}  ${k}`);
}

function checkIcs(files) {
  const problems = [];
  const uids = new Map();
  for (const f of files) {
    const raw = readFileSync(f.file, "utf8");
    const lines = raw.split("\r\n");
    if (!raw.endsWith("\r\n")) problems.push(`${f.name}: missing final CRLF`);
    for (const line of lines) {
      if (Buffer.byteLength(line, "utf8") > 75 && !line.startsWith(" ")) {
        problems.push(`${f.name}: unfolded line of ${Buffer.byteLength(line)} octets`);
        break;
      }
    }
    if (raw.match(/^DTSTART:(?!\d{8}T\d{6}Z)/m)) problems.push(`${f.name}: malformed DTSTART`);
    if ((raw.match(/BEGIN:VEVENT/g) || []).length !== (raw.match(/END:VEVENT/g) || []).length) {
      problems.push(`${f.name}: unbalanced VEVENT`);
    }
    for (const uid of raw.match(/^UID:(.+)/gm) || []) {
      const seenIn = uids.get(uid) || new Set();
      seenIn.add(f.name);
      uids.set(uid, seenIn);
    }
  }
  // UIDs may repeat only between the combined file and its per-club sources.
  for (const [uid, names] of uids) {
    if (names.size > 2) problems.push(`uid ${uid} reused across ${[...names].join(", ")}`);
    if (names.size === 2 && ![...names].includes("Sports Calendar — all clubs")) {
      problems.push(`uid ${uid} duplicated in ${[...names].join(", ")}`);
    }
  }
  return problems;
}

const icsProblems = checkIcs(files);
if (icsProblems.length) {
  console.error("\nICS self-check FAILED:");
  for (const p of icsProblems.slice(0, 20)) console.error("  ", p);
  process.exitCode = 1;
} else {
  console.log("ICS self-check: ok (folding, timestamps, UIDs)");
}

await writeFile(
  path.join(ROOT, ".cache", "report.json"),
  JSON.stringify({ generatedAt, report, timeConfidence, comps }, null, 2)
);
